### ISSUE TITLE
[Begginer] How to install python ?

### ISSUE THREAD

**Issue by axel584** [big-data-europe/docker-hadoop#109]
Hi,
I would like to try an hadoop cluster with a python script.
I launch the cluster with "docker-compose up -d" => it's work fine
I log in the namenode with "docker exec -it namenode /bin/bash" => it's work fine
I try to search the python package with "apt search python" but I found nothing which seem to be a python interpreter.
I would like to add "pip" and the "mrjob" package...

Thank you for your help,

Axel

**Comment by Gianlucamariani1996** [comment]
Hi, 
I've done these sequentially: 
- "docker exec -i -t -u root namenode /bin/bash" to enter in the namenode 
in container: 
- "apt-get update -y"
- "apt-get install -y python3"
and then:
- hadoop jar /opt/hadoop-3.2.1/share/hadoop/tools/lib/hadoop-streaming-3.2.1.jar -mapper <container-mapper-file-path> -reducer <container-reducer-file-path> -input <hdfs-input-file-path> -output <hdfs-output-file-path>
It's work fine

Gianluca

**Comment by Gianlucamariani1996** [comment]
Hi,
I've done these sequentially:
"docker exec -i -t -u root namenode /bin/bash" to enter in the namenode
in container:
"apt-get update -y"
"apt-get install -y python3"
and then:
hadoop jar /opt/hadoop-3.2.1/share/hadoop/tools/lib/hadoop-streaming-3.2.1.jar -mapper <container-mapper-file-path> -reducer <container-reducer-file-path> -input <hdfs-input-file-path> -output <hdfs-output-file-path>
It's work fine for me.
Gianluca

**Comment by Gianlucamariani1996** [comment]
Hi, 

I've done this sequentially: 
"docker exec -i -t -u root namenode /bin/bash" to enter in the namenode
in container: 
"apt-get update -y"
"apt-get install -y python3" 
"hadoop jar /opt/hadoop-3.2.1/share/hadoop/tools/lib/hadoop-streaming-3.2.1.jar -mapper "container-mapper-file-path" -reducer "container-reducer-file-path" -input "hdfs-input-file-path" -output "hdfs-output-file-path""
it's work fine for me. 

Gianluca

**Comment by axel584** [comment]
Thank you very much, "apt update" was the missing command ;-)
