### ISSUE TITLE
Apache Impala

### ISSUE THREAD

**Issue by natedogs911** [big-data-europe/docker-hadoop#11]
Hello,

Just curious if anyone is actively developing a docker impala container to plugin to this ecosystem?
I'm just getting started trying to assemble a docker hadoop stack with the following,

HDFS
Hive
Spark
Kafka
Impala

Just looking to keep from duplicating someone else's work.

Thanks

**Comment by earthquakesan** [comment]
hi @natedogs911!

We are not using Impala inside BDE project. Not sure if anyone from community did the work.

**Comment by natedogs911** [comment]
Thanks for the reply @earthquakesan 
I'm going to try viewing impala as a service that can run in another container with it's own HDFS nodes.
This is a temporary solution.

I can probably make it work as an add on to the hadoop cluster assuming i understand where all of the hdfs config files are.
I think i saw an issue in one of your repo's explaining it, i'll keep looking.
If things work out i'm not sure if you are interested in a PR for an impala container but let me know.
