### ISSUE TITLE
Can not connect to Ressourcemanager 

### ISSUE THREAD

**Issue by feridtola** [big-data-europe/docker-hadoop#129]
Hi guys,
(i´m new to docker)
i´m not able to connect nodemanager and ressourcemanager. I´m getting the following informations/errors: 

nodemanager3     | [30/100] try in 5s once again ...
nodemanager      | [31/100] check for resourcemanager:8088...
nodemanager      | [31/100] resourcemanager:8088 is not available yet
nodemanager      | [31/100] try in 5s once again ...
historyserver    | [31/100] check for resourcemanager:8088...

2022-07-01 17:39:23,104 INFO ipc.Client: Retrying connect to server: resourcemanager/172.18.0.2:8032. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS). 

I restarted the docker several time but still it does not work. Any idea what i can do next?

**Comment by luispablosegovia** [comment]
Hi feridtola! What did you do to solve this issue? I got the same ... thanks!
