### ISSUE TITLE
compatibility between containers with different base hadoop versions

### ISSUE THREAD

**Issue by natedogs911** [big-data-europe/docker-hadoop#14]
Hello,

Do you see any issue with using different hadoop versions among containers with different roles?

for instance if i'm running docker-hive containers with hadoop 2.8 and want to add a service to the cluster built from hadoop-base 2.7 due to OS version constraints/availability etc.
Would that cause any issues that you are aware of?

I have not experienced a problem as of yet, but as things usually are you won't experience a problem until much further down the road.

Thanks

**Comment by earthquakesan** [comment]
Hi @natedogs911 !

Apologies for late reply.

Different versions are not guaranteed to work together. However, in this particular case (hadoop 2.7, 2.8) it might work out. In general you should run a simple integration test for your particular case and see if everything is working fine. For example, a simple mapreduce application or simple file operations on HDFS.
