### ISSUE TITLE
Can I suggest a new function?

### ISSUE THREAD

**Issue by tasdf** [big-data-europe/docker-hadoop#15]
1. Can you add the Kylin to this project?

Thanks!

**Comment by earthquakesan** [comment]
Hi @tasdf!

The BDE project is almost over (December is the last month). I don't think, that we will be able to add any new components by the end of the project.
On other hand, we are open source and welcome contributions. You may add Kylin, and I will be available to support you in case of questions.

Kind regards,
Ivan Ermilov.
