### ISSUE TITLE
deployment in overlay network (swarm mode) not working

### ISSUE THREAD

**Issue by gmouchakis** [big-data-europe/docker-hadoop#21]
I tried to deploy a hadoop cluster in an overlay network and the datanodes could not connect to the namenode. Namenode reports that the reverse IP resolution for the specific node fails. The same exception is reported at the datanode.

To fix this set `HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check=false`

Bellow the reported error
`datanode1.1.rdz8cymlzo24@slave1    | 18/05/22 12:50:22 INFO datanode.DataNode: Block pool BP-579303948-10.0.0.11-1526993259750 (Datanode Uuid null) service to namenode2/10.0.0.10:8020 beginning handshake with NN
datanode1.1.rdz8cymlzo24@slave1    | 18/05/22 12:50:22 ERROR datanode.DataNode: Initialization failed for Block pool BP-579303948-10.0.0.11-1526993259750 (Datanode Uuid null) service to namenode2/10.0.0.10:8020 Datanode denied communication with namenode because hostname cannot be resolved (ip=10.0.0.13, hostname=10.0.0.13): DatanodeRegistration(0.0.0.0:50010, datanodeUuid=c990d411-7fa1-43b4-a7fa-f45fed48147b, infoPort=50075, infoSecurePort=0, ipcPort=50020, storageInfo=lv=-56;cid=CID-a856ef45-e3f7-4896-9973-543c07777c95;nsid=90446212;c=0)
datanode1.1.rdz8cymlzo24@slave1    |    at org.apache.hadoop.hdfs.server.blockmanagement.DatanodeManager.registerDatanode(DatanodeManager.java:863)
datanode1.1.rdz8cymlzo24@slave1    |    at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.registerDatanode(FSNamesystem.java:4529)
datanode1.1.rdz8cymlzo24@slave1    |    at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.registerDatanode(NameNodeRpcServer.java:1279)
datanode1.1.rdz8cymlzo24@slave1    |    at org.apache.hadoop.hdfs.protocolPB.DatanodeProtocolServerSideTranslatorPB.registerDatanode(DatanodeProtocolServerSideTranslatorPB.java:95)
datanode1.1.rdz8cymlzo24@slave1    |    at org.apache.hadoop.hdfs.protocol.proto.DatanodeProtocolProtos$DatanodeProtocolService$2.callBlockingMethod(DatanodeProtocolProtos.java:28539)
datanode1.1.rdz8cymlzo24@slave1    |    at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:616)
datanode1.1.rdz8cymlzo24@slave1    |    at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:969)
datanode1.1.rdz8cymlzo24@slave1    |    at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2049)
datanode1.1.rdz8cymlzo24@slave1    |    at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2045)
datanode1.1.rdz8cymlzo24@slave1    |    at java.security.AccessController.doPrivileged(Native Method)
datanode1.1.rdz8cymlzo24@slave1    |    at javax.security.auth.Subject.doAs(Subject.java:422)
datanode1.1.rdz8cymlzo24@slave1    |    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
datanode1.1.rdz8cymlzo24@slave1    |    at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2043)
`

**Comment by earthquakesan** [comment]
Hi @gmouchakis ! There is working docker compose in hbase repo. See this [env file](https://github.com/big-data-europe/docker-hbase/blob/master/distributed/hadoop.env) for details.

**Comment by gmouchakis** [comment]
Yes, setting `HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check=false` either in the compose file or in the docker run command works. Since you managed to import files using the hdfs command then maybe it is a different issue. Do you get the same `Initialization failed` error from the nodes?

**Comment by xavs** [comment]
Thanks for the quick response!
I'm running it through docker swarm, as a stack, in a cluster with 2 nodes. 
The initialization of the namenode and the datanodes works fine only if I do  `HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check=true`
otherwise only 1 datanode is started. Should I have the datanodes as different services instead of a 
global scheduling mode service (it's the way it gets created now, creating a service replica in each node)

Also, I also had to adjust the run.sh script for the namenode with 
`$HADOOP_PREFIX/bin/hdfs --config $HADOOP_CONF_DIR namenode -format $CLUSTER_NAME -clusterid $CLUSTER_NAME`
So the cluster id would remain constant (the -clusterid was missing) making it a different cluster id every time an issue happened

**Comment by xavs** [comment]
I just realised that the issue I'm having is with the docker-hbase repo, not this one, sorry for the confusion
