### ISSUE TITLE
How to use this container with another java/tomcat container?

### ISSUE THREAD

**Issue by hpaknia** [big-data-europe/docker-hadoop#22]
While I have my own java container, do I need to have java in this container? Can I use this container with another java/tomcat container?
Sorry if this question does not make much sense. Please let me know if you need clarification.

**Comment by gmouchakis** [comment]
Can you be more specific about what are you trying to do? Maybe provide an example?
In any case, the hadoop images from this repo have the following java version installed

```
openjdk version "1.8.0_111"                                                                                                                                                                                                                                                    
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2~bpo8+1-b14)                                                                                                                                                                                                           
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)
```

**Comment by hpaknia** [comment]
What I mean is that in my LAMP stack I install PHP in one container and Mysql in another. Now I already have a java container. When I add Hadoop container do I need to install java again in the new container?

**Comment by gmouchakis** [comment]
If I understand your question correctly, you don't need to install java again.
This issue is unrelated to this repository though so I'll close it.
