### ISSUE TITLE
Not able to access web uis

### ISSUE THREAD

**Issue by aahmed-vzw** [big-data-europe/docker-hadoop#24]
Here is output I got from docker network. What IP address should I use to access uis?

docker network list
NETWORK ID          NAME                    DRIVER              SCOPE
532de5548fae        docker-hadoop_default   bridge              local

docker network inspect docker-hadoop_default
[
    {
        "Name": "docker-hadoop_default",
        "Id": "532de5548fae05ec73401584d8d745a242d48880aba7431654d29bcae43c787c",
        "Created": "2018-08-04T00:31:40.0297858Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.29.0.0/16",
                    "Gateway": "172.29.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "01a2683d5861d879bfb760237da459430a23c4380342b982af392ecb15be40b8": {
                "Name": "datanode3",
                "EndpointID": "6395431456b043799cd5ec35cf28de2eedc3d440d6da3035cd8bf84f7c127cdd",
                "MacAddress": "02:42:ac:1d:00:03",
                "IPv4Address": "172.29.0.3/16",
                "IPv6Address": ""
            },
            "0c1ac1c3f75bb3372a0c5fc7ebc0e76d879c3e5c10f58d91c92d73a393dafd31": {
                "Name": "resourcemanager",
                "EndpointID": "f230411a390ae9f544ce1548861300d33c7506a6ab695501b0c7cdb363532632",
                "MacAddress": "02:42:ac:1d:00:06",
                "IPv4Address": "172.29.0.6/16",
                "IPv6Address": ""
            },
            "8affe1a3b2a89b8e384ce25e1161b39ba4f4376f51071954fa423f7e85fbc05d": {
                "Name": "historyserver",
                "EndpointID": "c63c9d103aad8328e54503c9015442a3f9bf0f8fd97ef7a8107242f3b2b82073",
                "MacAddress": "02:42:ac:1d:00:07",
                "IPv4Address": "172.29.0.7/16",
                "IPv6Address": ""
            },
            "9a307d47e485c8da103a26e9f8ff42262a1e7389cc08e0497f73144367906bed": {
                "Name": "datanode2",
                "EndpointID": "d2d674aefbe8000e80d73be8d3402884f8d357a5d9b5a957024aec650f8f2823",
                "MacAddress": "02:42:ac:1d:00:04",
                "IPv4Address": "172.29.0.4/16",
                "IPv6Address": ""
            },
            "b92efbfaa1275937ca6193d300175107f13bfc655b5492b1947a28248c4c540e": {
                "Name": "nodemanager1",
                "EndpointID": "7d0e7d747e326cc88bbea45e5ea34bb1d2cf082569683420ce8285b0a368dae9",
                "MacAddress": "02:42:ac:1d:00:08",
                "IPv4Address": "172.29.0.8/16",
                "IPv6Address": ""
            },
            "c510a8be2178487214fbe7b14e5bd06285b746afff6787b3f6394f6d8d259b22": {
                "Name": "datanode1",
                "EndpointID": "e0639cc31ad421711584f5c01fdc848f521473c95e0ef54eb5865a38e907770d",
                "MacAddress": "02:42:ac:1d:00:05",
                "IPv4Address": "172.29.0.5/16",
                "IPv6Address": ""
            },
            "f90c3696b7246724ec6438c2bbb67430612ee7fded231afabd09bdc86ed5c488": {
                "Name": "namenode",
                "EndpointID": "238d110ad84fe88855d6c26451358d735c487c88ad6b04c80b4411b08f9b797e",
                "MacAddress": "02:42:ac:1d:00:02",
                "IPv4Address": "172.29.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]

**Comment by gmouchakis** [comment]
Use the value of  `IPv4Address` for each container. In your example, the namenode UI can be accessed from `http://172.29.0.2:50070/dfshealth.html#tab-overview`. For the rest of the URLs check the README.
