### ISSUE TITLE
Starting namenode + datanode(s) before resourcemanager

### ISSUE THREAD

**Issue by kartoch** [big-data-europe/docker-hadoop#3]
resourcemanager cannot start if it cannot write to the HDFS, so it is require to wait that namenode + datanode(s) are ready.

At the present time the only solution is to start in two steps:

```
> docker-compose up -d namenode datanode1 datanode2 datanode3
[...]
> docker-compose up -d resourcemanager historyserver nodemanager1
```

**Comment by earthquakesan** [comment]
@kartoch this can be solved with healthchecks now. Check this one for example:
https://github.com/big-data-europe/docker-spark/blob/2.0.0-hadoop2.7-hive-java8/docker-compose.yml

I will update the docker-compose snippets accordingly.
