### ISSUE TITLE
Debian 9: Jessie repositories moved

### ISSUE THREAD

**Issue by Fubukimaru** [big-data-europe/docker-hadoop#33]
Hello!

First of all, thanks for your work.

Debian 8 is outdated now, so the repositories doesn't work as expected, which means that the docker can't be built.

There are two solutions as related in this post: https://unix.stackexchange.com/questions/508724/failed-to-fetch-jessie-backports-repository

- Change to Debian 9
- Use the archive repositories

Of course the first one is the most desirable. Is there any plan on solving this?

Thanks,
Alberto.

**Comment by gmouchakis** [comment]
@Fubukimaru please check commit https://github.com/big-data-europe/docker-hadoop/commit/9d1b0e78c762f5d90699e3b451d7eed8a6631d92

**Comment by Fubukimaru** [comment]
Looks good, thanks!
