### ISSUE TITLE
task k7yssbdrd1kzsrckahj8oapjm has not been scheduled,

### ISSUE THREAD

**Issue by YouAreMyLove** [big-data-europe/docker-hadoop#39]
I just run it:
docker stack deploy -c docker-compose-v3.yml hadoop

get the Error:
Error grabbing logs: rpc error: code = Unknown desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: task k7yssbdrd1kzsrckahj8oapjm has not been scheduled

**Comment by RamjiVE** [comment]
Im facing the same issue, DO you have solution?

**Comment by worp1900** [comment]
same error, any solutions?
