### ISSUE TITLE
cant access interfaces

### ISSUE THREAD

**Issue by hasrants** [big-data-europe/docker-hadoop#4]
I am running this using docker on Ubuntu 16.04 LS. I am unable to access any of the interfaces once I startup this docker-hadoop cluster. I dropped all my firewall rules to be sure. I see the ip addresses for each using docker network inspect hadoop but none of them work when.

**Comment by earthquakesan** [comment]
@hasrants can you please provide a command with which you are starting the cluster. Are you using Windows, *nix or Mac?

**Comment by earthquakesan** [comment]
Can't confirm the bug, closing
