### ISSUE TITLE
make wordcount fails OSX

### ISSUE THREAD

**Issue by otosky** [big-data-europe/docker-hadoop#48]
Can someone help me troubleshoot the issue I'm having with `make wordcount`?

Running that command yields this error:

> docker run --network docker-hadoop_default --env-file hadoop.env bde2020/hadoop-base: hdfs dfs -mkdir -p /input/
> docker: invalid reference format.
> See 'docker run --help'.
> make: *** [wordcount] Error 125

**Comment by MingfeiPan** [comment]
Your input image format missed a tag, rewrite the Makefile then add a tag manually

from 
```
current_branch := $(shell git rev-parse --abbrev-ref HEAD)
```
to

```
current_branch := latest
```

**Comment by reevelau** [comment]
https://github.com/big-data-europe/docker-hadoop/blob/master/Makefile#L3

If you want to preserve the tag and branch settings, you can change the line to this on a Mac.

```
current_branch := $(shell git branch --show-current)
```

**Comment by otosky** [comment]
Thanks - @MingfeiPan's change pointed me in the right direction.  

Just an edit for those who haven't updated git in a while - "--show-current" requires `git` 2.22.0+

**Comment by dendihandian** [comment]
for this `make wordcount` command, which container should I enter to execute?
