### ISSUE TITLE
Lack of license

### ISSUE THREAD

**Issue by lr4d** [big-data-europe/docker-hadoop#49]
Me and a colleague have used/adapted some of the Dockerfiles and config provided here.
To keep in line with regulations ("Generally speaking, the absence of a license means that the default copyright laws apply."), I'd appreciate if you could add a license to this repo.

**Comment by gmouchakis** [comment]
Hi @lr4d. As stated at https://github.com/big-data-europe/README the default licence for all the BDE components is the MIT license. You can find the licence file at the aforementioned repository.

**Comment by lr4d** [comment]
Thanks
