### ISSUE TITLE
docker-compose up fails, manifest unknown

### ISSUE THREAD

**Issue by dav-ell** [big-data-europe/docker-hadoop#53]
```
$ docker-compose up
ERROR: manifest for bde2020/hadoop-namenode:2.0.0-hadoop3.1.3-java8 not found: manifest unknown: manifest unknown
```

Can be fixed by changing `2.0.0-hadoop3.1.3-java8` to `latest` in `docker-compose.yml`. Looks like there's no tag in docker hub for `2.0.0-hadoop3.1.3-java8`.

**Comment by gmouchakis** [comment]
@dav-ell thanks for pointing this out. This will be fixed soon.

**Comment by gmouchakis** [comment]
fixed.

**Comment by GuillaumeDesforges** [comment]
I got the error

```
Pulling namenode (bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8)...
ERROR: manifest for bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8 not found: manifest unknown: manifest unknown
```

fixed changing to `bde2020/hadoop-namenode:2.0.0-hadoop3.1.3-java8`

**Comment by gmouchakis** [comment]
Hi @GuillaumeDesforges. Probably the images were still building when you tried to pull. They are ready now.

**Comment by GuillaumeDesforges** [comment]
Thanks for the follow up. My humble recommendation would be to make the changes in a PR, and lock the merge until the Docker images are available on the Hub, as it would prevent such "false alarms" (unlikely to happen, but it happened nevertheless for me).
