### ISSUE TITLE
The IP of the datanode in the HDFS dfsadmin -report does not match the container IP of the actual datanode

### ISSUE THREAD

**Issue by ktpktr0** [big-data-europe/docker-hadoop#84]
I use swarm to install the Hadoop cluster，All nodes have run successfully. In bde2020/Hadoop resource cemanager:2.0.0-hadoop3.2.1-java8 And bde2020/Hadoop- namenode:2.0.0-hadoop3.2.1-java8 This problem exists in both of them.

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Execute on the namenode:

# hdfs dfsadmin -report

Configured Capacity: 104747708416 (97.55 GB)

Present Capacity: 46329274722 (43.15 GB)

DFS Remaining: 46329262080 (43.15 GB)

DFS Used: 12642 (12.35 KB)

DFS Used%: 0.00%

Replicated Blocks:

Under replicated blocks: 0

Blocks with corrupt replicas: 0

Missing blocks: 0

Missing blocks (with replication factor 1): 0

Low redundancy blocks with highest priority to recover: 0

Pending deletion blocks: 0

Erasure Coded Block Groups:

Low redundancy block groups: 0

Block groups with corrupt internal blocks: 0

Missing block groups: 0

Low redundancy blocks with highest priority to recover: 0

Pending deletion blocks: 0

-------------------------------------------------

Live datanodes (3):

Name: 10.0.1.165:9866 (10.0.1.165)

Hostname: 2f4d391384f2

Decommission Status : Normal

Configured Capacity: 28163575808 (26.23 GB)

DFS Used: 4214 (4.12 KB)

Non DFS Used: 22699933578 (21.14 GB)

DFS Remaining: 5463638016 (5.09 GB)

DFS Used%: 0.00%

DFS Remaining%: 19.40%

Configured Cache Capacity: 0 (0 B)

Cache Used: 0 (0 B)

Cache Remaining: 0 (0 B)

Cache Used%: 100.00%

Cache Remaining%: 0.00%

Xceivers: 1

Last contact: Mon Aug 31 02:53:52 UTC 2020

Last Block Report: Mon Aug 31 02:51:05 UTC 2020

Num of Blocks: 5

Name: 10.0.1.166:9866 (10.0.1.166)

Hostname: 7d553d4d90f0

Decommission Status : Normal

Configured Capacity: 48420556800 (45.10 GB)

DFS Used: 4214 (4.12 KB)

Non DFS Used: 20661768074 (19.24 GB)

DFS Remaining: 27758784512 (25.85 GB)

DFS Used%: 0.00%

DFS Remaining%: 57.33%

Configured Cache Capacity: 0 (0 B)

Cache Used: 0 (0 B)

Cache Remaining: 0 (0 B)

Cache Used%: 100.00%

Cache Remaining%: 0.00%

Xceivers: 1

Last contact: Mon Aug 31 02:53:52 UTC 2020

Last Block Report: Mon Aug 31 02:51:04 UTC 2020

Num of Blocks: 5

Name: 10.0.1.167:9866 (10.0.1.167)

Hostname: 57233aef706c

Decommission Status : Normal

Configured Capacity: 28163575808 (26.23 GB)

DFS Used: 4214 (4.12 KB)

Non DFS Used: 15056732042 (14.02 GB)

DFS Remaining: 13106839552 (12.21 GB)

DFS Used%: 0.00%

DFS Remaining%: 46.54%

Configured Cache Capacity: 0 (0 B)

Cache Used: 0 (0 B)

Cache Remaining: 0 (0 B)

Cache Used%: 100.00%

Cache Remaining%: 0.00%

Xceivers: 1

Last contact: Mon Aug 31 02:53:52 UTC 2020

Last Block Report: Mon Aug 31 02:51:07 UTC 2020

Num of Blocks: 5
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Other datanodes:

# ip a

1: lo: <LOOPBACK,UP,LOWER_ UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000

link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00

inet 127.0.0.1/8 scope host lo

valid_ lft forever preferred_ lft forever

4004: eth0@if4005 : <BROADCAST,MULTICAST,UP,LOWER_ UP> mtu 1450 qdisc noqueue state UP group default

link/ether 02:42:0a:00:01:af brd ff:ff:ff:ff:ff:ff link-netnsid 0

inet 10.0.1.175/24 brd 10.0.1.255 scope global eth0

valid_ lft forever preferred_ lft forever

4006: eth1@if4007 : <BROADCAST,MULTICAST,UP,LOWER_ UP> mtu 1500 qdisc noqueue state UP group default

link/ether 02:42:ac:12:00:04 brd ff:ff:ff:ff:ff:ff link-netnsid 1

inet 172.18.0.4/16 brd 172.18.255.255 scope global eth1

valid_ lft forever preferred_ lft forever

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# ip a

1: lo: <LOOPBACK,UP,LOWER_ UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000

link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00

inet 127.0.0.1/8 scope host lo

valid_ lft forever preferred_ lft forever

24612: eth0@if24613 : <BROADCAST,MULTICAST,UP,LOWER_ UP> mtu 1450 qdisc noqueue state UP group default

link/ether 02:42:0a:00:01:ae brd ff:ff:ff:ff:ff:ff link-netnsid 0

inet 10.0.1.174/24 brd 10.0.1.255 scope global eth0

valid_ lft forever preferred_ lft forever

24614: eth1@if24615 : <BROADCAST,MULTICAST,UP,LOWER_ UP> mtu 1500 qdisc noqueue state UP group default

link/ether 02:42:ac:14:00:06 brd ff:ff:ff:ff:ff:ff link-netnsid 1

inet 172.20.0.6/16 brd 172.20.255.255 scope global eth1

valid_ lft forever preferred_ lft forever

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# ip a

1: lo: <LOOPBACK,UP,LOWER_ UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000

link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00

inet 127.0.0.1/8 scope host lo

valid_ lft forever preferred_ lft forever

4247: eth0@if4248 : <BROADCAST,MULTICAST,UP,LOWER_ UP> mtu 1450 qdisc noqueue state UP group default

link/ether 02:42:0a:00:01:ad brd ff:ff:ff:ff:ff:ff link-netnsid 0

inet 10.0.1.173/24 brd 10.0.1.255 scope global eth0

valid_ lft forever preferred_ lft forever

4249: eth1@if4250 : <BROADCAST,MULTICAST,UP,LOWER_ UP> mtu 1500 qdisc noqueue state UP group default

link/ether 02:42:ac:12:00:04 brd ff:ff:ff:ff:ff:ff link-netnsid 1

inet 172.18.0.4/16 brd 172.18.255.255 scope global eth1

valid_ lft forever preferred_ lft forever

Has anyone ever encountered such a problem

**Comment by ktpktr0** [comment]
I have configured the host name in the YML file, and the hosts of all Hadoop nodes are correct, but there is still an error in datanode IP. I also got the same error in version 3.2.1. It works when I use other Hadoop images that are not mounted env files.

**Comment by ktpktr0** [comment]
I have solved the problem

**Comment by tammam1998** [comment]
Hi @ktpktr0, 

Can you please share how you solved the problem. I'm facing the same problem atm. Thanks
